Feature/mattermost
StackStorm/st2chatops pull request #65
Opened 2017-02-21 20:02 UTC by emedvedev

Package Mattermost adapter (https://github.com/loafoe/hubot-matteruser) as a dependency and update the `st2chatops.env` file with a Mattermost example. 

The corresponding `hubot-stackstorm` PR with extra formatting support for Mattermost is already merged: https://github.com/StackStorm/hubot-stackstorm/pull/132

2017-03-10 14:07 UTC, arm4b requested changes

2017-03-10 14:07 UTC, armab commented on st2chatops.env
> +# export MATTERMOST_HOST=CHANGE-ME-PLEASE
`export HUBOT_ADAPTER=mattermost` is missing

2017-03-14 07:49 UTC, emedvedev commented on st2chatops.env
> +# export MATTERMOST_HOST=CHANGE-ME-PLEASE
Done

2017-03-14 11:58 UTC, arm4b approved these changes

2017-03-14 13:02 UTC, merged