WIP: Let's upgrade to node 6
StackStorm/st2chatops pull request #78
Opened 2017-07-12 17:36 UTC by lakshmi-kannan

2017-07-12 19:00 UTC, armab commented
Upgrading to node 6 will also pull the following: 
- Changing the node version in `st2chatops` package deb/rpm dependency
- Changing node version in curl|bash installer
- Changing the node version in ansible-st2 installer
- st2docs update for manual installation steps
- https://github.com/StackStorm/st2-packages/issues/437 probably can be closed

first ideas, but could be also something else ¯\_(ツ)_/¯

2017-07-26 14:40 UTC, armab commented on debian/st2chatops.service
> +StandardError=syslog+console
Does that fix hubot logging bug described here: https://github.com/StackStorm/st2-packages/issues/300 ?

If so, please update `st2chatops.service` for rpm as well.

2017-07-26 14:48 UTC, lakshmi-kannan commented on debian/st2chatops.service
> +StandardError=syslog+console
It does not. This directive instructs journalctl to write to console which should get logged to /var/log according to docs but it doesn't. So sad.

2017-07-26 15:05 UTC, armab commented on debian/st2chatops.service
> +StandardError=syslog+console
Feels like the truth is out there.

Let's try this for `st2chatops.service`: 
```diff
- ExecStart=/opt/stackstorm/chatops/bin/hubot $DAEMON_ARGS
+ ExecStart=exec bin/hubot $DAEMON_ARGS >> /var/log/st2/st2chatops.log 2>&1
```

2017-07-26 15:15 UTC, armab commented on package.json
> +    "hubot-slack"       : "^4.3.4"
From the reports in GitHub https://github.com/StackStorm/st2chatops/issues/56#issuecomment-285562378, https://github.com/StackStorm/st2docs/issues/418 and community, this should also fix proxy support for Slack adapter :+1: 
cc @ytjohn

2017-08-14 16:04 UTC, arm4b requested changes

2017-08-14 16:04 UTC, armab commented on debian/control
> +Depends: nodejs (>= 6.0.0)
Considering `nodejs` epopeya https://github.com/StackStorm/ops-infra/pull/206, please pin node versions to `6` for both deb/rpm.
So we won't install any node7 or node8 or whatever in future.

2017-08-16 18:28 UTC, arm4b approved these changes

2017-08-17 16:39 UTC, merged