Change default logging to INFO
StackStorm/st2chatops pull request #84
Opened 2017-08-23 19:10 UTC by Mierdin

Closes #77

2017-08-23 20:10 UTC, LindsayHill approved these changes

2017-08-23 20:14 UTC, armab commented
Could this potentially break any ChatOps CI or similar we rely in our e2e tests @humblearner?
If so, we might need to inject `debug` loglevel in internal environment after this gets merged.

2017-08-23 20:26 UTC, humblearner requested changes
This will not only break chatopsCI, it will also break the self check script: https://github.com/StackStorm/st2chatops/blob/master/scripts/self-check.sh#L187 and it will add a step for new users, changing the debug level, who may have problem setting up st2chatops for the first time. It would be better to add step in docs to decrease verbosity.

2017-08-23 20:59 UTC, Mierdin commented
This change was actually requested by a user, that the messages are too verbose, and I'm inclined to agree - INFO is a common default log level. I'd prefer that we make this change, and follow @armab suggestion of injecting a DEBUG loglevel for our internal CI so we don't break our own CI

On a related note, the CircleCI checks have passed thus far, so if we're expecting CI to break, maybe something need adjusted.

2017-08-23 21:38 UTC, humblearner commented
@Mierdin: I have seen the conversation in #chatops community channel. I agree with you that the default log level should be `info`, but here it has been `debug` for a while, for a reason. Moreover, this is **not** related to CircleCI checks for this repo. This will cause failure in ChatopsCI (robot tests). 

**Please make changes  at following locations as well:**

1. ChatOps CI in our [e2e_tests](https://github.com/StackStorm/st2tests/tree/master/robotfm_tests/chatopsCI)

2. Troubleshooting chatops for new users using this [guide](https://docs.stackstorm.com/troubleshooting/basic_chatops_troubleshooting.html) and [self-check-script](https://github.com/StackStorm/st2chatops/blob/master/scripts/self-check.sh)


However, I still don't agree with this change, because:
- On one hand, as an advanced user, I can go ahead and change the log level in `st2chatops.env` file. 
- On the other, as a new user,  I first change the log level to `debug` and then use the script. (Unless we make changes in the troubleshooting guide and the self-check script.)

Also, note, you will still see `INFO` logs every two minutes about the loaded commands:

```
Aug 23 19:31:24 st2demo004 hubot[8914]: [Wed Aug 23 2017 19:31:24 GMT+0000 (UTC)] INFO Connecting...
Aug 23 19:31:24 st2demo004 hubot[8914]: [Wed Aug 23 2017 19:31:24 GMT+0000 (UTC)] DEBUG Loading adapter slack
Aug 23 19:31:22 st2demo004 systemd[1]: Started StackStorm service st2chatops.
Aug 23 19:31:22 st2demo004 systemd[1]: Stopped StackStorm service st2chatops.
Aug 23 19:31:22 st2demo004 systemd[1]: Stopping StackStorm service st2chatops...
Aug 23 19:31:17 st2demo004 hubot[29402]: [Wed Aug 23 2017 19:31:17 GMT+0000 (UTC)] INFO 7 commands are loaded
Aug 23 19:31:17 st2demo004 hubot[29402]: [Wed Aug 23 2017 19:31:17 GMT+0000 (UTC)] DEBUG Added command: demo reset diskspace on {{hostname}} - Reset diskspace demo
Aug 23 19:31:17 st2demo004 hubot[29402]: [Wed Aug 23 2017 19:31:17 GMT+0000 (UTC)] DEBUG Added command: disk clean {{hostname}} {{directory=/var/log}} - Run diskspace
clean up from chatops
Aug 23 19:31:17 st2demo004 hubot[29402]: [Wed Aug 23 2017 19:31:17 GMT+0000 (UTC)] DEBUG Added command: disk clean {{directory}} on {{hostname}} - Run diskspace clean
up from chatops
Aug 23 19:31:17 st2demo004 hubot[29402]: [Wed Aug 23 2017 19:31:17 GMT+0000 (UTC)] DEBUG Added command: pack show {{ pack }} - Show information about the pack from Sta
ckStorm Exchange.
Aug 23 19:31:17 st2demo004 hubot[29402]: [Wed Aug 23 2017 19:31:17 GMT+0000 (UTC)] DEBUG Added command: pack show <pack> - Show information about the pack from StackSt
orm Exchange.
Aug 23 19:31:17 st2demo004 hubot[29402]: [Wed Aug 23 2017 19:31:17 GMT+0000 (UTC)] DEBUG Added command: pack search {{ query }} - Search for packs in StackStorm Exchan
ge and other directories.
Aug 23 19:31:17 st2demo004 hubot[29402]: [Wed Aug 23 2017 19:31:17 GMT+0000 (UTC)] DEBUG Added command: pack search <query> - Search for packs in StackStorm Exchange and other directories.
Aug 23 19:31:17 st2demo004 hubot[29402]: [Wed Aug 23 2017 19:31:17 GMT+0000 (UTC)] DEBUG Added command: pack install {{ packs }} - Install/upgrade StackStorm packs.
Aug 23 19:31:17 st2demo004 hubot[29402]: [Wed Aug 23 2017 19:31:17 GMT+0000 (UTC)] DEBUG Added command: pack install <gitUrl>[,<gitUrl>] - Install/upgrade StackStorm packs.
Aug 23 19:31:17 st2demo004 hubot[29402]: [Wed Aug 23 2017 19:31:17 GMT+0000 (UTC)] DEBUG Added command: pack install <pack>[,<pack>] - Install/upgrade StackStorm packs.
Aug 23 19:31:17 st2demo004 hubot[29402]: [Wed Aug 23 2017 19:31:17 GMT+0000 (UTC)] DEBUG Added command: pack get {{ pack }} - Get information about installed StackStorm pack.
Aug 23 19:31:17 st2demo004 hubot[29402]: [Wed Aug 23 2017 19:31:17 GMT+0000 (UTC)] DEBUG Added command: pack get <pack> - Get information about installed StackStorm pa:
```

2017-08-23 22:38 UTC, LindsayHill commented
Q: how many other apps ship with DEBUG logs on by default?

And if we are determined to ship with DEBUG, then surely we should at least sort out this other pack issue of no log rotate script?

2018-10-24 23:13 UTC, Mierdin commented
Closing for now, since this is a bit stale. Feel free to pick up where I left off on the branch.

2018-10-25 10:34 UTC, armab commented
The change itself is good. Maybe @blag can pick it up in future and update the st2tests as part of the initiative to rectify st2chatops.

2018-11-17 08:41 UTC, cognifloyd requested changes
In order for the ansible smoke-test to succeed, it needs to be able to override this environment var. I suggest setting this to info only as a default if the var is not already set.

https://github.com/StackStorm/ansible-st2/blob/7dbcc49bc0adc3b2502b6f4caa07769f25fbf0b4/roles/st2smoketests/tasks/st2chatops.yml#L7-L8

2018-11-17 08:41 UTC, cognifloyd commented on st2chatops.env
> +export HUBOT_LOG_LEVEL=info
```suggestion
export HUBOT_LOG_LEVEL=${HUBOT_LOG_LEVEL:-info}
```

2018-11-17 13:24 UTC, arm4b commented on st2chatops.env
> +export HUBOT_LOG_LEVEL=info
Good catch! :+1:

2018-11-18 01:37 UTC, cognifloyd approved these changes
Looks good!

2018-11-19 17:22 UTC, cognifloyd commented
> * On the other, as a new user,  I first change the log level to `debug` and then use the script. (Unless we make changes in the troubleshooting guide and the self-check script.)

Maybe the self-check script (which I have not used or reviewed in detail) needs to modify the log level on the fly similar to how the ansible smoke-test sets the variable:

2021-12-05 14:56 UTC, closed without merging